### ISSUE TITLE
deblur checkpoint Unexpected key(s) in state_dict: "ratio_1", "ratio_2"

### ISSUE THREAD

**Issue by ronsoohyeong** [yjzhang96/Motion-ETR#1]
Dear author,
the pretrained deblur checkpoint seems to be inconsistent with the provided code. 
I did this after setting blur_direction=deblur.
In fact, in models/network.py, class Decoder_offset001 lacks ratio_1 and ratio_2.
Can you please guide on how to move on? Thanks in advance.
~~~
 $ sh run_test.sh 
------------ Options -------------
aspect_ratio: 1.0
batchSize: 8
blur_direction: deblur
checkpoints_dir: pretrain_models
continue_train: False
dataroot: ./datasets/Gopro_align_data
dataset_mode: aligned
display_id: 0
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
loadSizeX: 720
loadSizeY: 1280
max_dataset_size: inf
model: dcn
nThreads: 2
n_offset: 15
name: MTR_Gopro_quad
no_crop: True
no_flip: False
ntest: inf
offset_mode: quad
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./exp_results/
serial_batches: False
verbose: False
which_direction: AtoB
which_epoch: latest
-------------- End ----------------
Opt.nThreads =  1
dataset [AlignedDataset] was created
CustomDatasetDataLoader
--------- MA_Deblur : loaded offset_network_path ./pretrain_models/latest_net_offset_quadratic.pth
--------- BaseModel : loading model pretrain_models/MTR_Gopro_quad/latest_net_deblur.pth
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    model = create_model(opt)
  File "/media/hdd/Downloads/Work/deblur/blur_kernel_estimation/Motion-ETR/models/models.py", line 12, in create_model
    model = MA_Deblur(opt)
  File "/media/hdd/Downloads/Work/deblur/blur_kernel_estimation/Motion-ETR/models/deblur_model_MA_offset_pre.py", line 67, in __init__
    self.load_network(self.MANet, 'deblur', opt.which_epoch)
  File "/media/hdd/Downloads/Work/deblur/blur_kernel_estimation/Motion-ETR/models/base_model.py", line 62, in load_network
    self.load_GPUS(network,save_path)
  File "/media/hdd/Downloads/Work/deblur/blur_kernel_estimation/Motion-ETR/models/base_model.py", line 77, in load_GPUS
    model.load_state_dict(new_state_dict)
  File "/home/ron_lee/anaconda3/envs/pt1.1py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DMPHN_decoder_offset:
	Unexpected key(s) in state_dict: "deblur_net.decoder_lv1.ratio_1", "deblur_net.decoder_lv1.ratio_2", "deblur_net.decoder_lv2.ratio_1", "deblur_net.decoder_lv2.ratio_2", "deblur_net.decoder_lv3.ratio_1", "deblur_net.decoder_lv3.ratio_2". 
    ~~~

**Comment by yjzhang96** [comment]
Thank you for pointing that out. The model I upload is an old version with parameters ratio_1 and ratio_2. I have uploaded the newer one, which should solve the problem.
